config/routes.rb
Blog::Application.routes.draw do
  devise_for :users
  resources :users

  get 'tags/:tag', to: 'posts#index', as: :tag
  resources :posts do 
    resources :comentarios
  end
  
  root to: 'posts#index'

end

app/models/comentario.rb
# == Schema Information
#
# Table name: comentarios
#
#  id         :integer          not null, primary key
#  autor      :string(255)
#  conteudo   :text
#  post_id    :integer
#  created_at :datetime
#  updated_at :datetime
#

class Comentario < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id                  :integer          not null, primary key
#  titulo              :string(255)
#  conteudo            :text
#  created_at          :datetime
#  updated_at          :datetime
#  avatar_file_name    :string(255)
#  avatar_content_type :string(255)
#  avatar_file_size    :integer
#  avatar_updated_at   :datetime
#

class Post < ActiveRecord::Base
	has_many :comentarios
	validates :titulo, :presence => true, :length => {:minimum => 10}
	validates :conteudo, :presence => true
	has_attached_file :avatar, :styles => { :medium => "600x600>", :small => "400x400>" }, :default_url => "/images/:style/missing.png"

	geocoded_by :address
	after_validation :geocode

	acts_as_taggable
	ActsAsTaggableOn.remove_unused_tags = true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  name                   :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
# Prevent CSRF attacks by raising an exception. 
# For APIs, you may want to use :null_session instead.


before_action :configure_permitted_parameters, if: :devise_controller?

protect_from_forgery

protected

def configure_permitted_parameters 
		devise_parameter_sanitizer.for(:sign_up)  << :name #{|user| user.permit(:name,:email,:password,:password_confirmation)} 

  			devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:name, :email) }
end

def authorize_blogger! 
	if user_signed_in? 
	return 
	elsif user_signed_in? 
	flash[:notice] = 'You must be an authorized blogger to do that' 
	redirect_to :root 
	else 
	flash[:notice] = 'You need to sign in first' 
	redirect_to new_user_session_path 
   end 
  end
 end

app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
  before_filter :authorize_blogger!, :only => [:destroy]

  def create
    @post = Post.find(params[:post_id])
    @comentario = @post.comentarios.create(comentario_params)
    #@comentario = @post.comentarios.create(params[:comentarios])
    if @comentario.autor == nil
      @comentario.autor = current_user.name
      @comentario.save
    end
    redirect_to post_path(@post)

  end

  def comentario_params
    params.require(:comentario).permit(:autor,:conteudo,:post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comentario = @post.comentarios.find(params[:id])
    @comentario.destroy
    redirect_to post_path(@post)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authorize_blogger!, :except =>[:index, :show]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    if params[:tag]
      @posts = Post.tagged_with(params[:tag]).paginate(:order => 'created_at DESC', :page => params[:page], :per_page => 5)
    else
      @posts = Post.all.paginate(:order => 'created_at DESC', :page => params[:page], :per_page => 5)
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
    @hash = Gmaps4rails.build_markers(@post) do |post, marker|
      marker.lat post.latitude
      marker.lng post.longitude
    end
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:titulo, :conteudo, :avatar, :address, :tag_list)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authorize_blogger!
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comentarios/_form.html.erb
<%= remote_form_for(@comentario) do |f| %>
  <% if @comentario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comentario.errors.count, "error") %> prohibited this comentario from being saved:</h2>

      <ul>
      <% @comentario.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  
  <div class="field">
    <%= f.label :autor %><br>
    <%= f.text_field :autor %>
  </div>
  <div class="field">
    <%= f.label :conteudo %><br>
    <%= f.text_area :conteudo %>
  </div>
  <div class="field">
    <%= f.label :post_id %><br>
    <%= f.text_field :post_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comentarios/edit.html.erb
<h1>Editing comentario</h1>

<%= render 'form' %>

<%= link_to 'Show', @comentario %> |
<%= link_to 'Back', comentarios_path %>

app/views/comentarios/index.html.erb
<h2>Listing comentarios</h2>

<table>
  <thead>
    <tr>
      <th>Autor</th>
      <th>Conteudo</th>
      <th>Post</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @comentarios.each do |comentario| %>
      <tr>
        <td><%= comentario.autor %></td>
        <td><%= comentario.conteudo %></td>
        <td><%= comentario.post %></td>
        <td><%= link_to 'Show', comentario %></td>
        <td><%= link_to 'Edit', edit_comentario_path(comentario) %></td>
        <td><%= link_to 'Destroy', comentario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comentario', new_comentario_path %>

app/views/comentarios/new.html.erb
<h1>New comentario</h1>

<%= render 'form' %>

<%= link_to 'Back', comentarios_path %>

app/views/comentarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Autor:</strong>
  <%= @comentario.autor %>
</p>

<p>
  <strong>Conteudo:</strong>
  <%= @comentario.conteudo %>
</p>

<p>
  <strong>Post:</strong>
  <%= @comentario.post %>
</p>

<%= link_to 'Edit', edit_comentario_path(@comentario) %> |
<%= link_to 'Back', comentarios_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!--<link href= "/dist/css/bootstrap.min.css", rel="stylesheet">-->
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Blog dos Zés" %></title>
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Blog do Zés" %>">
  <%= stylesheet_link_tag    "bootstrap", "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "bootstrap", "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <header>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'Blog dos Zés', root_path, class: 'navbar-brand' %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-ex1-collapse">
          <ul class="nav navbar-nav">
            <li><a href="../posts/new">New Post</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <div id="secondaryContent" class="text-left">
              <%= render 'devise/common/session' %>
            </div>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container -->
    </nav></br>
  </header>

  <div class="container">
  
    <div class="row">
      <div class="col-lg-8">
        <main role="main">
          <%=yield%>
        <main>
      </div>

      <div class="col-lg-4">
        <div class="well">
          <h4>Categorias</h4>
            <div class="row">
              <div class="col-lg-12">
                <ul class="list-unstyled">
                  
                  <li>
                  </li>

                  <li><a href="#dinosaurs">Dinosaurs</a></li>
                  <li><a href="#spaceships">Spaceships</a></li>
                  <li><a href="#fried-foods">Fried Foods</a></li>
                  <li><a href="#wild-animals">Wild Animals</a></li>
                </ul>
              </div>
            </div>
        </div><!-- /well -->
      </div>
    </div>
  </div>

</body>

</html>

app/views/posts/_form.html.erb
<%= form_for(@post, :html => { :multipart => true }) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <form role="form">
  <div class="form-group">
    <label for="InputTitulo">Título</label>
    <%= f.text_field :titulo, :class => "form-control", :placeholder => "Insira o título do post" %>
  </div>
  <div class="form-group">
    <label for="InputAddress">Localização</label>
    <%= f.text_field :address, :class => "form-control", :placeholder => "Insira a sua localização" %>
  </div>
  <div class="form-group">
    <label for="InputConteudo">Conteúdo</label>
    <%= f.text_area :conteudo, :rows => 8, :class => "form-control", :placeholder => "Insira conteúdo" %>
  </div>
  <div class="form-group">
    <label for="InputTags">Tags</label>
    <%= f.text_field :tag_list, :class => "form-control", :placeholder =>"Tags (separated by commas)" %><br />
  </div>
  <div class="form-group">
    <label for="InputImagem">Imagem</label>
    <%= f.file_field :avatar %>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>

<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Back to post', @post, :class=>"btn btn-default"%>
<%= link_to 'Back', posts_path, :class=>"btn btn-default"%>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <h1><%= link_to post.titulo, post %></h1>
  <hr>
  <p>Created: <%=post.created_at%> | Edit: <%=post.updated_at%></p>
  <hr>
  <div class="img-responsive">
    <p style="text-align: center">
      <%= image_tag post.avatar.url (:small)%>
    </p>
  </div>
  <!--<img src="post.avatar.url" class="img-responsive">-->
  <hr>
  <p><%= post.conteudo %></p>
  <p>Tags: <%= raw post.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %></p>
  <p>
  <%= link_to 'Ver Mais', post, class: 'btn btn-primary' %>
  <% if user_signed_in? %>
    <%= link_to 'Editar', edit_post_path(post), class: 'btn btn-default' %>
    <%= link_to 'Excluir', post, class: 'btn btn-default', :confirm => 'Tem certeza?', :method => :delete %>
  <% end %>
  </p>
<%end%>
      
<div class = "pager">
  <%= will_paginate @posts %>
</div>

app/views/posts/new.html.erb
<h2>New Post</h2>

<%= render 'form' %>

<a class="btn btn-default" href="/../posts" role="button">Back</a>

app/views/posts/show.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
<p class="notice"><%= notice %></p>

<h2><%= @post.titulo %></h2>

<p style="text-align: center">
  <%= image_tag @post.avatar.url (:medium)%>
</p>

<p><%= @post.conteudo %></p> 

<h5>Local de submissão do post</h5>
<div style='width: 800px;'>
  <div id="map" style='width: 400px; height: 200px;'></div>
</div>

<script type="text/javascript">
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
</script>

<h3>Comentários :</h3>
<% @post.comentarios.each do |comentario| %>

  <p>
    <b>Autor:</b>
    <%= comentario.autor %>
    
  </p>

  <p>
    <b>Comentario</b>
    <%= comentario.conteudo %>
  </p>
  <p>
    <b>Criado em:</b>
    <%= comentario.created_at %>
  </p>
  
<p>
  <% if user_signed_in? %>
  <%= link_to 'Apagar Comentario', [comentario.post, comentario],
              :confirm => 'Tem certeza?',
              :method => :delete %>
<% end %>
</p>

<hr />
<% end %>
 
<h2>Adicione um comentario:</h2>
<%= form_for([@post, @post.comentarios.build]) do |f| %>
  
  <% if !user_signed_in? %>
  <form role="form">
    <div class="form-group">
      <label for="InputAutor">Autor</label>
      <%= f.text_field :autor, :class => "form-control", :placeholder => "Insira Autor" %>
    </div>
    <div class="form-group">
      <label for="InputConteudo">Conteúdo</label>
      <%= f.text_area :conteudo, :rows => 3, :class => "form-control", :placeholder => "Insira conteúdo" %>
    </div>
  </form>
  <% else %>
    <form role="form">
      <div class="form-group">
        <label for="InputConteudo">Conteúdo</label>
        <%= f.text_area :conteudo, :rows => 3, :class => "form-control", :placeholder => "Insira conteúdo" %>
      </div>
    </form>
  <% end %>
  <button type="submit" class="btn btn-default">Submit</button>
<% end %>
 
<br />
<% if user_signed_in? %>
  <%= link_to 'Editar Post', edit_post_path(@post), :class=>"btn btn-default" %>
  <%= link_to 'Back', posts_path, :class=>"btn btn-primary" %>
<%else%>
  <%= link_to 'Back', posts_path, :class=>"btn btn-primary" %>
<%end%>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
      <div class="field">
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </div>
   <div><%= f.label :password %><br />
  <%= f.password_field :password %></div>

  <div><%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation %></div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Lista de utilizadores</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>


  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>